on:  
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, reopened, edited, closed, review_requested]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, edited]


jobs:
  printJob:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  postcommenttoslack:    
    name: Print event
    runs-on: ubuntu-latest
    steps:
    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "text": "@Michel COMMENT PR - ${{ github.event.pull_request_review.comment }}\n *Created by:* <${{ github.event.pull_request.user.login }}>",
            "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "@Michel Comment PR - ${{ job.status }}\n${{ github.event.pull_request_review.comment }} \n *Created by:* <${{ github.event.pull_request.user.login }}>"
              }
            }
          ] 
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
   
  # PR-review_comment:
  #   name: Review the PR
  #   runs-on: ubuntu-22.04
    
  #   steps:
  #   - name: Send custom JSON data to Slack workflow
  #     id: slack
  #     uses: slackapi/slack-github-action@v1.23.0
  #     with:
  #       # This data can be any valid JSON from a previous step in the GitHub Action
  #       payload: |
  #         {
  #           "text": "${{ pull_request_review.comment }}"
            
  #         }
  #     env:
  #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}