name: thollander/actions-comment-pull-request@v1 
on:  
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, reopened, edited, closed, review_requested]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      
    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: 'Loading ...'
    
    - name: Edit PR comment
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: 'Content loaded ! (edited)'
        comment_includes: 'Loading'
