on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Loading ...'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Edit PR comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: 'Content loaded ! (edited)'
          comment_includes: 'Loading'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}